CREATE TABLE AUTORES (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    NACIONALIDADE VARCHAR(100),
    DATA_NASCIMENTO DATE
);

CREATE TABLE USUARIOS (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE LIVROS (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    TITULO VARCHAR(200) NOT NULL,
    ISBN VARCHAR(20),
    GENERO VARCHAR(100),
    ANO_PUBLICACAO INT,
    AUTOR_ID BIGINT NOT NULL,

    CONSTRAINT FK_LIVROS_AUTORES
        FOREIGN KEY (AUTOR_ID)
        REFERENCES AUTORES(ID)
);